# Generated by Django 4.1.5 on 2023-01-13 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chat_owner_usertochat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now=True),
                ),
                ("text", models.TextField(max_length=100)),
                ("execute_at", models.DateTimeField()),
                ("executed", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "scheduled_message",
                "verbose_name_plural": "scheduled_message",
                "db_table": "scheduled_message",
            },
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["execute_at"], name="scheduled_m_execute_495b75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmessage",
            index=models.Index(
                fields=["executed"], name="scheduled_m_execute_a7a086_idx"
            ),
        ),
    ]
